-- MySQL Script generated by MySQL Workbench
-- Thu Jan 22 10:46:05 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema COMERCIO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema COMERCIO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `COMERCIO` DEFAULT CHARACTER SET utf8 ;
USE `COMERCIO` ;

-- -----------------------------------------------------
-- Table `COMERCIO`.`PROVEEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMERCIO`.`PROVEEDOR` (
  `idPROVEEDOR` INT NOT NULL COMMENT 'CIF del proveedor',
  `NOMBRE_PROVEEDOR` VARCHAR(45) NOT NULL,
  `DIRECCION` VARCHAR(150) NOT NULL,
  `NACIONALIDAD` VARCHAR(45) NOT NULL,
  `REPRESENTANTE` VARCHAR(45) NOT NULL,
  `CORREO` VARCHAR(150) NOT NULL,
  `TELEFONO` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`idPROVEEDOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COMERCIO`.`PRODUCTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMERCIO`.`PRODUCTO` (
  `idPRODUCTO` INT NOT NULL,
  `NOMBRE_PRODUCTO` VARCHAR(45) NOT NULL,
  `DESCRIPCION` VARCHAR(150) NULL,
  `PRECIO` FLOAT NOT NULL,
  `STOCK` INT NOT NULL COMMENT 'Número de unidades disponibles',
  `FOTO` VARCHAR(250) NULL COMMENT 'Enlace de la foto',
  `PAIS` VARCHAR(45) NOT NULL COMMENT 'País de procedencia',
  `idPROVEEDOR` INT NOT NULL,
  PRIMARY KEY (`idPRODUCTO`),
  INDEX `fk_PRODUCTO_PROVEEDOR_idx` (`idPROVEEDOR` ASC) ,
  CONSTRAINT `fk_PRODUCTO_PROVEEDOR`
    FOREIGN KEY (`idPROVEEDOR`)
    REFERENCES `COMERCIO`.`PROVEEDOR` (`idPROVEEDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `COMERCIO`.`PROVEEDOR`
-- -----------------------------------------------------
START TRANSACTION;
USE `COMERCIO`;
INSERT INTO `COMERCIO`.`PROVEEDOR` (`idPROVEEDOR`, `NOMBRE_PROVEEDOR`, `DIRECCION`, `NACIONALIDAD`, `REPRESENTANTE`, `CORREO`, `TELEFONO`) VALUES (1, 'Muebles Olajuwon', 'Calle 富恩拉夫拉达', 'Chino', 'Kaicedo', 'olajuwonmuebles@mail.com', '623949503');
INSERT INTO `COMERCIO`.`PROVEEDOR` (`idPROVEEDOR`, `NOMBRE_PROVEEDOR`, `DIRECCION`, `NACIONALIDAD`, `REPRESENTANTE`, `CORREO`, `TELEFONO`) VALUES (2, 'Mobile Trending', 'Calle Sun', 'Estado Unidense', 'Lebron', 'mobiletrend@mail.com', '645764832');
INSERT INTO `COMERCIO`.`PROVEEDOR` (`idPROVEEDOR`, `NOMBRE_PROVEEDOR`, `DIRECCION`, `NACIONALIDAD`, `REPRESENTANTE`, `CORREO`, `TELEFONO`) VALUES (3, 'Fa Aire', 'Calle Estevao', 'Brasileño', 'Vinicius', 'faaire@mail.com', '648936582');

COMMIT;


-- -----------------------------------------------------
-- Data for table `COMERCIO`.`PRODUCTO`
-- -----------------------------------------------------
START TRANSACTION;
USE `COMERCIO`;
INSERT INTO `COMERCIO`.`PRODUCTO` (`idPRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCION`, `PRECIO`, `STOCK`, `FOTO`, `PAIS`, `idPROVEEDOR`) VALUES (2, 'Movil', 'Móviles de última generación', 700, 67, 'Movil.jpg', 'Estados Unidos', 2);
INSERT INTO `COMERCIO`.`PRODUCTO` (`idPRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCION`, `PRECIO`, `STOCK`, `FOTO`, `PAIS`, `idPROVEEDOR`) VALUES (3, 'Ventilador', 'Ventiladores de techo', 250, 10, 'Ventilador.jpg', 'Brasil', 3);
INSERT INTO `COMERCIO`.`PRODUCTO` (`idPRODUCTO`, `NOMBRE_PRODUCTO`, `DESCRIPCION`, `PRECIO`, `STOCK`, `FOTO`, `PAIS`, `idPROVEEDOR`) VALUES (1, 'Muebles', 'Muebles para decorar la casa', 300, 25, 'Muebles.jpg', 'China', 1);

COMMIT;

